# Generated by Django 5.0.6 on 2024-07-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('FIR', 'fire'), ('EAR', 'earth'), ('AIR', 'air'), ('WAT', 'water')], default='FIR', max_length=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ARI', 'aries'), ('LEO', 'leo'), ('SAG', 'sagittarius'), ('TAU', 'taurus'), ('VIR', 'virgo'), ('CAP', 'capricorn'), ('GEM', 'gemini'), ('LIB', 'libra'), ('AQU', 'aquarius'), ('CAN', 'cancer'), ('SCO', 'scorpio'), ('PIS', 'pisces')], default='ARI', max_length=12)),
                ('elem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope.elem')),
            ],
        ),
    ]
