# Generated by Django 5.0.6 on 2024-07-12 14:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='begin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='elem',
            name='title',
            field=models.CharField(choices=[('FIR', 'Fire'), ('EAR', 'Earth'), ('AIR', 'Air'), ('WAT', 'Water')], default='FIR', max_length=4),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='elem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horoscope.elem'),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='title',
            field=models.CharField(choices=[('ARI', 'Aries'), ('LEO', 'Leo'), ('SAG', 'Sagittarius'), ('TAU', 'Taurus'), ('VIR', 'Virgo'), ('CAP', 'Capricorn'), ('GEM', 'Gemini'), ('LIB', 'Libra'), ('AQU', 'Aquarius'), ('CAN', 'Cancer'), ('SCO', 'Scorpio'), ('PIS', 'Pisces')], default='ARI', max_length=12),
        ),
    ]
