# Generated by Django 5.0.6 on 2024-07-12 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_horoscope_begin_date_horoscope_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='begin_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
