# Generated by Django 5.0.6 on 2024-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_alter_horoscope_begin_date_alter_horoscope_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='begin_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='end_date',
            field=models.IntegerField(null=True),
        ),
    ]
