# Generated by Django 5.0.6 on 2024-07-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0004_alter_horoscope_begin_date_alter_horoscope_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
