# Generated by Django 5.0.6 on 2024-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0005_horoscope_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elem',
            name='image',
            field=models.FileField(null=True, upload_to='horoscope'),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='image',
            field=models.FileField(null=True, upload_to='horoscope'),
        ),
    ]
